Repository athenianco/athenian-webapp, pull requests merged in 2020-03, with the labels that each got.

#85 Fixes
  src/js/components/ui/Typography.jsx
  src/js/pages/prototypes/types/HorizontalBarChart.jsx
  src/js/pages/prototypes/types/PositiveNegativeBarChart.jsx
  src/js/pages/prototypes/types/VerticalBarChart.jsx
  src/js/pages/templates/Simple.jsx
  src/js/res/palette.js
  src/sass/_variables.scss
  src/sass/base/_typography.scss
  src/sass/components/_filters.scss
  src/sass/components/_pipeline.scss
Labels: enhancement

#86 Styling badges and minor additional style fixing
  src/js/components/ui/Badge.jsx
  src/sass/_overrides.scss
  src/sass/components/_badges.scss
  src/sass/components/_tables.scss
  src/sass/main.scss
Labels: enhancement

#87 Styling tables to match the prototype
  src/fonts/cerebrisans-light.woff
  src/js/components/pipeline/PullRequests.jsx
  src/sass/base/_typography.scss
  src/sass/components/_badges.scss
  src/sass/components/_tables.scss
Labels: enhancement

#89 Minor fixes and adding TODOs
  src/js/components/pipeline/Thumbnails.jsx
  src/js/services/api/index.js
  src/js/services/format.js
Labels: enhancement

#91 Persist the current API schema
  .gitignore
  Makefile
  src/js/services/api/openapi.v0.0.39.yaml
Labels: enhancement

#93 Update API client to 1.0.5
  .gitignore
  Makefile
  package.json
  src/js/services/api/README.md
  src/js/services/api/index.js
  src/js/services/api/openapi-client/.openapi-generator-ignore
  src/js/services/api/openapi-client/.openapi-generator/VERSION
  src/js/services/api/openapi-client/ApiClient.js
  src/js/services/api/openapi-client/api/DefaultApi.js
  src/js/services/api/openapi-client/api/FilterApi.js
  src/js/services/api/openapi-client/api/MetricsApi.js
  src/js/services/api/openapi-client/api/RegistrationApi.js
  src/js/services/api/openapi-client/api/ReposetApi.js
  src/js/services/api/openapi-client/api/UserApi.js
  src/js/services/api/openapi-client/index.js
  src/js/services/api/openapi-client/model/Account.js
  src/js/services/api/openapi-client/model/CalculatedMetric.js
  src/js/services/api/openapi-client/model/CalculatedMetricValues.js
  src/js/services/api/openapi-client/model/CalculatedMetrics.js
  src/js/services/api/openapi-client/model/CodeBypassingPRsMeasurement.js
  src/js/services/api/openapi-client/model/Commit.js
  src/js/services/api/openapi-client/model/CommitFilter.js
  src/js/services/api/openapi-client/model/CommitGroupForFilterCommitsRequest.js
  src/js/services/api/openapi-client/model/CommitSignature.js
  src/js/services/api/openapi-client/model/CommitsGroupedByTime.js
  src/js/services/api/openapi-client/model/CreatedIdentifier.js
  src/js/services/api/openapi-client/model/FilterCommitsRequest.js
  src/js/services/api/openapi-client/model/FilterCommitsRequestAllOf.js
  src/js/services/api/openapi-client/model/FilterContribsOrReposRequest.js
  src/js/services/api/openapi-client/model/FilterPullRequestsRequest.js
  src/js/services/api/openapi-client/model/ForSet.js
  src/js/services/api/openapi-client/model/GenericError.js
  src/js/services/api/openapi-client/model/IncludedNativeUser.js
  src/js/services/api/openapi-client/model/IncludedNativeUsers.js
  src/js/services/api/openapi-client/model/InstallationProgress.js
  src/js/services/api/openapi-client/model/InvalidRequestError.js
  src/js/services/api/openapi-client/model/InvalidRequestErrorAllOf.js
  src/js/services/api/openapi-client/model/InvitationCheckResult.js
  src/js/services/api/openapi-client/model/InvitationLink.js
  src/js/services/api/openapi-client/model/InvitedUser.js
  src/js/services/api/openapi-client/model/MetricID.js
  src/js/services/api/openapi-client/model/NoSourceDataError.js
  src/js/services/api/openapi-client/model/NoSourceDataErrorAllOf.js
  src/js/services/api/openapi-client/model/PullRequest.js
  src/js/services/api/openapi-client/model/PullRequestMetricsRequest.js
  src/js/services/api/openapi-client/model/PullRequestParticipant.js
  src/js/services/api/openapi-client/model/PullRequestPipelineStage.js
  src/js/services/api/openapi-client/model/PullRequestSet.js
  src/js/services/api/openapi-client/model/PullRequestSetInclude.js
  src/js/services/api/openapi-client/model/PullRequestWith.js
  src/js/services/api/openapi-client/model/RepositorySetCreateRequest.js
  src/js/services/api/openapi-client/model/RepositorySetListItem.js
  src/js/services/api/openapi-client/model/TableFetchingProgress.js
  src/js/services/api/openapi-client/model/User.js
  src/js/services/api/openapi.1.0.5.yaml
  yarn.lock
Labels: enhancement

#90 Refactoring sizes for spacers and type sizes to make it more intuitive
  src/js/components/layout/Breadcrumbs.jsx
  src/js/components/layout/Navbar.jsx
  src/sass/_overrides.scss
  src/sass/base/_typography.scss
  src/sass/components/_badges.scss
  src/sass/components/_dropdowns.scss
  src/sass/components/_tables.scss
  src/sass/layout/_header.scss
Labels: enhancement

#94 Enhance debug experience on Makefiles
  Makefile
Labels: enhancement

#106 Minors
  Makefile
  src/js/components/pipeline/MainMetrics.jsx
  src/js/components/pipeline/PullRequests.jsx
  src/js/components/pipeline/StageMetrics.jsx
  src/js/components/pipeline/Thumbnails.jsx
  src/js/pages/pipeline/Body.jsx
  src/js/services/api/index.js
  src/js/services/format.js
  yarn.lock
Labels: enhancement

#111 Force deploy staging
  .travis.yml
  src/js/components/pipeline/StageMetrics.jsx
Labels: bug

#112 Clean how prototypes are defined
  src/js/Routes.jsx
  src/js/pages/datefilter/DateFilter.jsx
  src/js/pages/prototypes/Charts.jsx
  src/js/pages/prototypes/DateFilter.jsx
  src/js/pages/prototypes/charts/BubbleChart.jsx
  src/js/pages/prototypes/charts/HorizontalBarChart.jsx
  src/js/pages/prototypes/charts/PositiveNegativeBarChart.jsx
  src/js/pages/prototypes/charts/ScatterPlot.jsx
  src/js/pages/prototypes/charts/VerticalBarChart.jsx
  src/js/pages/prototypes/index.jsx
Labels: enhancement

#110 Use imported bootstrap-daterangepicker styles
  package.json
  src/sass/components/_datepicker.scss
  src/sass/main.scss
  yarn.lock
Labels: enhancement

#107 Add Summary Metrics chart into Overview & Stages
  docs/SummaryMetrics.md
  src/js/components/charts/FilledAreaChart.jsx
  src/js/components/pipeline/StageMetrics.jsx
  src/js/components/pipeline/Thumbnails.jsx
  src/js/context/Pipeline.jsx
  src/js/pages/Pipeline.jsx
  src/js/pages/pipeline/Body.jsx
  src/js/pages/pipeline/Overview.jsx
  src/js/pages/pipeline/Pipeline.jsx
  src/js/pages/pipeline/Stage.jsx
  src/js/services/api/index.js
  src/js/services/format.js
  src/sass/components/_pipeline.scss
Labels: enhancement

#115 Metrics groups
  src/js/Routes.jsx
  src/js/pages/insights/InsightLayouts.jsx
  src/js/pages/prototypes/MetricGroups.jsx
  yarn.lock
Labels: enhancement

#118 Add PRs tabs into stages
  src/js/components/layout/Tabs.jsx
  src/js/components/pipeline/PullRequests.jsx
  src/js/components/pipeline/StageMetrics.jsx
  src/js/pages/pipeline/Overview.jsx
  src/js/pages/pipeline/Pipeline.jsx
  src/js/pages/pipeline/Stage.jsx
  src/sass/base/_utilities.scss
  src/sass/components/_tabs.scss
  src/sass/main.scss
Labels: enhancement

#120 Horfix. Use default reposet when no repos
  src/js/pages/pipeline/Filters.jsx
Labels: bug

#122 Redirect the user to the home on loging.
  src/js/pages/auth/Login.jsx
Labels: enhancement

#123 Remove rb-datepicker, DatePicker prototype and restore tests in Travis
  .travis.yml
  package.json
  src/js/Routes.jsx
  src/js/components/charts/FilledAreaChart.jsx
  src/js/pages/pipeline/Filters.jsx
  src/js/pages/prototypes/DateFilter.jsx
  src/js/services/format.js
  yarn.lock
Labels: enhancement

#124 Fix warning. state setter should not be called from component body
  src/js/context/Breadcrumbs.jsx
Labels: bug

#127 Remove warnings
  Makefile
  package.json
  src/js/components/layout/Navbar.jsx
  src/js/components/pipeline/PullRequests.jsx
  src/js/components/ui/filters/MultiSelect.jsx
  src/js/pages/auth/Callback.jsx
  src/js/pages/pipeline/Overview.jsx
  src/js/pages/pipeline/Pipeline.jsx
  src/js/pages/prototypes/charts/BubbleChart.jsx
  src/js/pages/prototypes/charts/ScatterPlot.jsx
  src/js/res/palette.js
  src/js/services/api/index.js
  src/sass/_overrides.scss
  src/sass/components/_tables.scss
  yarn.lock
Labels: bug, enhancement

#128 Remove releases and leadTime mocks
  src/js/services/api/index.js
Labels: enhancement

#129 Bumb API version 1.0.5 -> 1.0.9
  Makefile
  src/js/services/api/openapi-client/ApiClient.js
  src/js/services/api/openapi-client/api/DefaultApi.js
  src/js/services/api/openapi-client/api/FilterApi.js
  src/js/services/api/openapi-client/api/MetricsApi.js
  src/js/services/api/openapi-client/api/RegistrationApi.js
  src/js/services/api/openapi-client/api/ReposetApi.js
  src/js/services/api/openapi-client/api/UserApi.js
  src/js/services/api/openapi-client/index.js
  src/js/services/api/openapi-client/model/Account.js
  src/js/services/api/openapi-client/model/CalculatedMetric.js
  src/js/services/api/openapi-client/model/CalculatedMetricValues.js
  src/js/services/api/openapi-client/model/CalculatedMetrics.js
  src/js/services/api/openapi-client/model/CodeBypassingPRsMeasurement.js
  src/js/services/api/openapi-client/model/Commit.js
  src/js/services/api/openapi-client/model/CommitFilter.js
  src/js/services/api/openapi-client/model/CommitGroupForFilterCommitsRequest.js
  src/js/services/api/openapi-client/model/CommitSignature.js
  src/js/services/api/openapi-client/model/CommitsGroupedByTime.js
  src/js/services/api/openapi-client/model/CreatedIdentifier.js
  src/js/services/api/openapi-client/model/FilterCommitsRequest.js
  src/js/services/api/openapi-client/model/FilterCommitsRequestAllOf.js
  src/js/services/api/openapi-client/model/FilterContribsOrReposRequest.js
  src/js/services/api/openapi-client/model/FilterPullRequestsRequest.js
  src/js/services/api/openapi-client/model/ForSet.js
  src/js/services/api/openapi-client/model/GenericError.js
  src/js/services/api/openapi-client/model/IncludedNativeUser.js
  src/js/services/api/openapi-client/model/IncludedNativeUsers.js
  src/js/services/api/openapi-client/model/InstallationProgress.js
  src/js/services/api/openapi-client/model/InvalidRequestError.js
  src/js/services/api/openapi-client/model/InvalidRequestErrorAllOf.js
  src/js/services/api/openapi-client/model/InvitationCheckResult.js
  src/js/services/api/openapi-client/model/InvitationLink.js
  src/js/services/api/openapi-client/model/InvitedUser.js
  src/js/services/api/openapi-client/model/MetricID.js
  src/js/services/api/openapi-client/model/NoSourceDataError.js
  src/js/services/api/openapi-client/model/NoSourceDataErrorAllOf.js
  src/js/services/api/openapi-client/model/PullRequest.js
  src/js/services/api/openapi-client/model/PullRequestMetricsRequest.js
  src/js/services/api/openapi-client/model/PullRequestParticipant.js
  src/js/services/api/openapi-client/model/PullRequestPipelineStage.js
  src/js/services/api/openapi-client/model/PullRequestProperty.js
  src/js/services/api/openapi-client/model/PullRequestSet.js
  src/js/services/api/openapi-client/model/PullRequestWith.js
  src/js/services/api/openapi-client/model/RepositorySetCreateRequest.js
  src/js/services/api/openapi-client/model/RepositorySetListItem.js
  src/js/services/api/openapi-client/model/TableFetchingProgress.js
  src/js/services/api/openapi-client/model/User.js
  src/js/services/api/openapi.1.0.9.yaml
Labels: enhancement

#130 Count releases
  docs/SummaryMetrics.md
  src/js/pages/pipeline/Pipeline.jsx
Labels: enhancement

#125 Integrate DateInterval calendar using "react-dates"
  package.json
  src/js/components/ui/filters/DateInterval.jsx
  src/js/pages/pipeline/Filters.jsx
  src/sass/components/_datepicker.scss
  yarn.lock
Labels: enhancement

#133 Update dependencies
  .travis.yml
  package.json
  yarn.lock
Labels: bug

#137 Implement accept/cancel buttons in the date filter
  src/js/components/ui/filters/DateInterval.jsx
  src/sass/components/_buttons.scss
Labels: enhancement

#145 Let the user to decide for any node >= v12
  package.json
Labels: enhancement

#148 Enhance PR tables
  src/js/components/pipeline/PullRequests.jsx
  src/js/pages/pipeline/Pipeline.jsx
  src/js/services/api/index.js
  src/js/services/prHelpers.js
Labels: enhancement

#150 Remove warnings
  src/js/components/pipeline/PullRequests.jsx
  src/js/pages/pipeline/Stage.jsx
  src/js/pages/prototypes/Tooltips.jsx
  src/js/services/api/index.js
Labels: bug, enhancement

#156 Use stage labels instead of pr stages
  src/js/components/pipeline/PullRequests.jsx
  src/js/pages/pipeline/Overview.jsx
  src/js/pages/pipeline/Stage.jsx
  src/js/services/prHelpers.js
  src/sass/components/_tables.scss
Labels: enhancement

#158 Some enhancements
  src/js/components/pipeline/MainMetrics.jsx
  src/js/components/pipeline/PullRequests.jsx
  src/sass/components/_tables.scss
Labels: enhancement
