Repository athenianco/athenian-webapp, pull requests merged in 2020-06, with the labels that each got.

#401 Add new Wip chart. Pull Requests per Repo
  src/js/components/charts/Tooltip.jsx
  src/js/components/insights/charts/library/VerticalBarChart.jsx
  src/js/components/insights/stages/merge/mergeDelays.jsx
  src/js/components/insights/stages/work-in-progress/index.jsx
  src/js/components/insights/stages/work-in-progress/pullRequestPerRepo.jsx
Labels: enhancement

#402 Hide Wip > Pull Requests per Repo from Prod
  src/js/components/insights/stages/work-in-progress/index.jsx
Labels: enhancement

#405 Remove variation badge in wait time for 1st review
  src/js/components/insights/stages/review/waitTimeFirstReview.jsx
Labels: enhancement

#409 New Chart: Merge > Abandoned work
  src/js/components/charts/Tooltip.jsx
  src/js/components/insights/charts/library/VerticalBarChart.jsx
  src/js/components/insights/stages/merge/abandonedWork.jsx
  src/js/components/insights/stages/merge/index.jsx
  src/js/components/insights/stages/review/pullRequestSize.jsx
  src/js/components/insights/stages/work-in-progress/pullRequestPerRepo.jsx
  src/js/services/format.js
Labels: enhancement

#410 Hide Abandoned Work chart in Prod
  src/js/components/insights/stages/merge/index.jsx
Labels: enhancement

#404 Let God Users to impersonate other users from their Profile settings page
  src/js/context/User.jsx
  src/js/pages/settings/Profile.jsx
  src/js/services/api/index.js
  src/sass/components/_forms.scss
Labels: enhancement

#414 Show error message when a component could not fetch data.
  src/js/components/DataWidget.jsx
  src/js/pages/pipeline/Body.jsx
  src/js/pages/pipeline/Stage.jsx
  src/js/services/api/index.js
Labels: bug, enhancement

#415 Avoid negative numbers in axis
  src/js/components/insights/charts/library/BubbleChart.jsx
  src/js/components/insights/charts/library/TimeSeries.jsx
Labels: bug, enhancement

#412 "Empty" message when there is no data for an insight
  src/js/components/DataWidget.jsx
  src/js/components/insights/Box.jsx
  src/js/components/insights/charts/library/TimeSeries.jsx
  src/js/components/insights/stages/merge/abandonedWork.jsx
  src/js/components/insights/stages/merge/mergeDelays.jsx
  src/js/components/insights/stages/review/pullRequestSize.jsx
  src/js/components/insights/stages/review/reviewActivity.jsx
  src/js/components/insights/stages/review/waitTimeFirstReview.jsx
  src/js/components/insights/stages/work-in-progress/createdPrs.jsx
  src/js/components/insights/stages/work-in-progress/mostActiveDevs.jsx
  src/js/components/insights/stages/work-in-progress/pullRequestPerRepo.jsx
  src/js/components/insights/stages/work-in-progress/pullRequestRatioFlow.jsx
  src/js/components/layout/Empty.jsx
  src/js/components/pipeline/StageMetrics.jsx
  src/sass/components/_charts.scss
Labels: enhancement

#424 Show stage-complete count in stage thumbnails
  src/js/pages/pipeline/Pipeline.jsx
  src/js/services/prHelpers.js
Labels: enhancement

#442 fix(DEV-125): Strange hover behavior on PR ratio flow chart
  src/js/components/insights/stages/work-in-progress/pullRequestRatioFlow.jsx
Labels: bug
