Repository athenianco/athenian-webapp, pull requests merged in 2020-05, with the labels that each got.

#293 Fix some random errors that broke the page
  src/js/components/charts/FilledAreaChart.jsx
  src/js/components/insights/stages/merge/mergeDelays.jsx
  src/js/components/insights/stages/review/reviewActivity.jsx
  src/js/components/insights/stages/review/waitTimeFirstReview.jsx
  src/js/components/insights/stages/work-in-progress/mostActiveDevs.jsx
  src/js/components/insights/stages/work-in-progress/pullRequestRatioFlow.jsx
  src/js/components/layout/Empty.jsx
  src/js/pages/pipeline/Body.jsx
  src/js/services/api/index.js
  src/js/services/format.js
Labels: bug

#295 Move component status into the StatusIndicator
  src/js/components/DataWidget.jsx
  src/js/components/pipeline/MainMetrics.jsx
  src/js/components/pipeline/PullRequests.jsx
  src/js/components/pipeline/StageMetrics.jsx
  src/js/components/pipeline/Thumbnails.jsx
  src/js/components/ui/Spinner.jsx
  src/js/pages/pipeline/Body.jsx
  src/js/pages/pipeline/Overview.jsx
  src/js/pages/pipeline/Stage.jsx
  src/js/res/palette.js
Labels: bug, enhancement

#296 Remove debug leftover
  src/js/components/pipeline/Thumbnails.jsx
Labels: bug

#297 Settings
  src/js/Routes.jsx
  src/js/pages/Settings.jsx
  src/js/pages/prototypes/ReleaseSettings.jsx
  src/js/pages/prototypes/TeamsSettings.jsx
  src/js/pages/settings/Profile.jsx
  src/js/pages/settings/Releases.jsx
  src/js/pages/settings/Team.jsx
  src/sass/components/_dropdowns.scss
Labels: enhancement

#242 Speedup Travis
  .travis.yml
  Dockerfile
Labels: enhancement

#311 Show success/error messages in toast
  package.json
  src/js/App.jsx
  src/js/pages/settings/Releases.jsx
  src/js/services/logger.jsx
  src/sass/main.scss
  yarn.lock
Labels: enhancement

#313 Enable filtering in Release and Team settings
  src/js/pages/Settings.jsx
  src/js/pages/settings/Releases.jsx
  src/js/pages/settings/Team.jsx
Labels: enhancement

#317 Read API errors
  src/js/services/api/index.js
  src/js/services/logger.jsx
Labels: enhancement

#319 Enable 'Settings' in user menu. Hide 'Teams' menu
  src/js/components/layout/Navbar.jsx
  src/js/pages/Settings.jsx
Labels: enhancement

#320 Enable Teams link in Settings aside for Staging
  src/js/pages/Settings.jsx
Labels: bug, enhancement

#322 Misc. Show errors sent by Sentry in the console
  src/js/components/charts/Tooltip.jsx
  src/js/components/ui/Typography.jsx
  src/js/pages/prototypes/Tooltips.jsx
  src/js/services/api/index.js
Labels: enhancement

#323 Flags to detect development or not Prod
  src/js/components/development/index.jsx
Labels: enhancement

#324 Handle empty badges
  src/js/components/development/index.jsx
  src/js/components/development/index.scss
  src/js/components/insights/KPI.jsx
  src/js/components/layout/Tabs.jsx
  src/js/components/pipeline/MainMetrics.jsx
  src/js/components/pipeline/Thumbnails.jsx
  src/js/components/ui/Badge.jsx
  src/js/components/ui/Typography.jsx
  src/js/services/format.js
  src/sass/base/_typography.scss
  src/sass/components/_badges.scss
Labels: bug, enhancement

#326 Releases pattern
  src/js/pages/settings/Releases.jsx
Labels: enhancement

#328 Clean old and no longer needed Prototypes
  src/images/empty-states/coming-soon.svg
  src/images/empty-states/no-data.svg
  src/js/Routes.jsx
  src/js/components/layout/Empty.jsx
  src/js/pages/prototypes/Charts.jsx
  src/js/pages/prototypes/EmptyStates.jsx
  src/js/pages/prototypes/MetricGroups.jsx
  src/js/pages/prototypes/Waiting.jsx
  src/js/pages/prototypes/charts/BubbleChart.jsx
  src/js/pages/prototypes/charts/HorizontalBarChart.jsx
  src/js/pages/prototypes/charts/ScatterPlot.jsx
  src/js/pages/prototypes/charts/VerticalBarChart.jsx
Labels: enhancement

#329 Overview bars
  src/js/components/pipeline/StageMetrics.jsx
  src/js/services/format.js
  src/sass/components/_pipeline.scss
Labels: bug

#336 Handle badge errors
  src/js/App.jsx
  src/js/components/insights/KPI.jsx
  src/js/components/insights/stages/work-in-progress/mostActiveDevs.jsx
  src/js/components/ui/Badge.jsx
  src/js/services/prHelpers.js
  src/js/smart-components/ErrorBoundary.jsx
Labels: bug, enhancement

#338 Fix divisions by zero and NaN when missing data
  src/js/components/insights/KPI.jsx
  src/js/components/insights/stages/review/waitTimeFirstReview.jsx
  src/js/pages/pipeline/Body.jsx
Labels: bug

#340 Close welcome
  package.json
  src/js/pages/Settings.jsx
  src/sass/base/_transitions.scss
  src/sass/main.scss
  yarn.lock
Labels: enhancement

#341 Fix local welcomed panel storage key
  src/js/pages/Settings.jsx
Labels: bug

#344 Filter PRs by repo title
  src/js/components/pipeline/PullRequests.jsx
  src/js/components/ui/Info.jsx
  src/sass/components/_tables.scss
  src/sass/components/_tooltips.scss
Labels: enhancement

#345 Let the user filter by repo name
  src/js/components/pipeline/PullRequests.jsx
Labels: bug

#347 Ratio flow
  src/js/components/insights/charts/library/TimeSeries.jsx
  src/js/components/insights/stages/work-in-progress/pullRequestRatioFlow.jsx
  src/js/pages/pipeline/Body.jsx
Labels: enhancement

#349 Use TimeSeries chart type instead of dupe FilledAreaChart
  src/js/components/charts/FilledAreaChart.jsx
  src/js/components/charts/TimeSeries.jsx
  src/js/components/insights/charts/library/TimeSeries.jsx
  src/js/components/pipeline/StageMetrics.jsx
Labels: enhancement

#352 Restore default Branch and Tag patterns when using Automatic strategy
  src/js/pages/settings/Releases.jsx
Labels: enhancement

#342 New alert styling and copy
  src/js/App.jsx
  src/js/pages/settings/Releases.jsx
  src/js/services/logger.jsx
  src/sass/components/_alerts.scss
Labels: enhancement

#355 Remove null values from Thumbnails and WaitTime1stReview
  src/js/components/charts/CleanAreaChart.jsx
  src/js/components/charts/Tooltip.jsx
  src/js/components/insights/charts/library/TimeSeries.jsx
  src/js/components/insights/stages/review/waitTimeFirstReview.jsx
  src/js/components/pipeline/StageMetrics.jsx
  src/js/services/format.js
Labels: enhancement

#356 Exclude WIP PRs from PullRequestSize chart
  src/js/components/insights/stages/review/pullRequestSize.jsx
  src/js/components/insights/stages/work-in-progress/mostActiveDevs.jsx
Labels: enhancement

#364 Chart created prs
  src/js/components/charts/Tooltip.jsx
  src/js/components/insights/charts/library/TimeSeries.jsx
  src/js/components/insights/charts/library/VerticalBarChart.jsx
  src/js/components/insights/stages/work-in-progress/createdPrs.jsx
  src/js/components/insights/stages/work-in-progress/index.jsx
Labels: enhancement

#382 Filter PRs using datatable.net search method
  src/js/components/pipeline/PullRequests.jsx
Labels: bug

#384 Sort PR table by custom label order
  src/js/components/pipeline/PullRequests.jsx
  src/js/services/prHelpers.js
  src/sass/components/_tables.scss
Labels: enhancement

#386 Use only active days for CreatedPRs chart average KPI
  src/js/components/insights/stages/work-in-progress/createdPrs.jsx
  src/js/components/layout/Footer.jsx
  src/js/pages/Settings.jsx
Labels: enhancement

#387 Pr size improvements
  src/js/components/insights/stages/review/pullRequestSize.jsx
  src/js/services/prHelpers.js
Labels: enhancement

#390 Change isInStage and extractCompletedStages logic for closed PRs
  src/js/services/prHelpers.js
Labels: enhancement

#391 Fix Horizontal Bar chart height depending in its content
  src/js/components/insights/charts/library/HorizontalBarChart.jsx
Labels: bug

#395 Enable Created PRs chart in prod
  src/js/components/insights/stages/work-in-progress/index.jsx
  src/js/services/prHelpers.js
Labels: enhancement

#396 Sort PRs table by label asc, creation desc
  src/js/components/pipeline/PullRequests.jsx
Labels: enhancement
